FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

ENV DEBIAN_FRONTEND=noninteractive
RUN sudo apt-get update \
 && sudo apt-get -y install --no-install-recommends \
      
      python3 \
      python3-pip \
      python3-dev \
      python3-wheel \
      python3-setuptools \
      python3-venv
      

